"""empty message

Revision ID: 3e513535dab
Revises: 537051d66f9
Create Date: 2015-05-19 17:02:28.766614

"""

# revision identifiers, used by Alembic.
revision = '3e513535dab'
down_revision = '537051d66f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
