"""empty message

Revision ID: 537051d66f9
Revises: 47f1ca470e4
Create Date: 2015-05-18 16:52:25.764916

"""

# revision identifiers, used by Alembic.
revision = '537051d66f9'
down_revision = '47f1ca470e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
